---
# Handlers for all roles
- name: Restart lightdm
  ansible.builtin.service:
    name: lightdm
    state: restarted
  become: true

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  become: true

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  become: true
